# Uncomment the following lines to enable RGB underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=25

# Uncomment the following lines to enable Nice!View
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_SYSTEM=y

# Uncomment the following line for power always on
CONFIG_ZMK_EXT_POWER=y

# Uncomment the following line for ZMK Studio
CONFIG_ZMK_STUDIO=y
